name: 'testoauth'
version: 0.0.1
description: A web server built using the shelf package.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  googleapis_auth: "^0.2.3+1"
  googleapis: any
  google_oauth2_client: any
  google_oauth2_jwt: any
  http: any

